### ISSUE TITLE
Difference between lesson code and written code

### ISSUE THREAD

**Issue by yahwehschica7** [learn-co-curriculum/react-hooks-react-router-programmatic-navigation#4]
### Canvas Link

https://github.com/yahwehschica7/react-hooks-react-router-programmatic-navigation

### Concern

I don't know if I'm reading it right, but it seems the code in VS is different than the code in the lesson. Only slightly, and I think the concept is still clear, but just thought you should know. Usually the code-along in the lesson is identical to what forks to my terminal. Thanks!

**Comment by lizbur10** [comment]
Hi @yahwehschica7 ! Thanks for bringing this to our attention. I have added an explanatory note about why there's a mismatch between what's in the lesson and what's in the attached code files. Note that you may not see the changes reflected in your Canvas course, but it will be present for students moving forward.

Thanks for contributing to the Flatiron School curriculum 💙
