### ISSUE TITLE
useHistory hook

### ISSUE THREAD

**Issue by chibukasia** [learn-co-curriculum/react-hooks-react-router-programmatic-navigation#6]
### Canvas Link

https://moringa.instructure.com/courses/86/assignments/5956?module_item_id=13465

### Concern

useHistory hook is no longer functional with the new versions of React. It was changed to useNavigate

### Suggested Changes

Update the content to use useNavigate

**Comment by lizbur10** [comment]
Hi @chibukasia ! This content has been updated to React Router v6 so I'm closing this issue. Thanks for contributing to the Flatiron School curriculum 💙
